int openWordsFile ();
void closeWordsFile ();
void getRandWord();
void printWord();
void garbegeCollector();
int getPlayerInput();
int Is5Letters(char *palabra);
void wordToUpper(char *palabra);
void resInit();
int *CheckPlayerGuess(int turn);
int checkResult(int *result);
void initializeGrid();
void FSstart();
void scooreStart();
void calculateScore(int *result, int turn);
int PedirCantPartidas();
void playRound();
void playGame();