int openWordsFile ();
void closeWordsFile ();
void getRandWord();
void printWord();
int getPlayerInput();
int Is5Letters(char *palabra);
void wordToUpper(char *palabra);
int *CheckPlayerGuess(int turn);
int checkResult(int *result);
void initializeGrid();